test-suites:
  it-rwx-jest:
    command: npx jest --testResultsProcessor=jest-junit --outputFile tmp/jest.xml
    results:
      path: tmp/jest.xml
    output:
      print-summary: true
    partition:
      command: |
        echo "=== Captain Partition Debug ==="
        echo "CIRCLE_NODE_INDEX: ${CIRCLE_NODE_INDEX}"
        echo "CIRCLE_NODE_TOTAL: ${CIRCLE_NODE_TOTAL}"
        echo "Current directory: $(pwd)"
        echo "Test files found by glob:"
        find tests/ -name "*.test.js" | head -10
        echo "Total test files: $(find tests/ -name "*.test.js" | wc -l)"
        echo "About to run Jest with partitioned files..."
        echo "================================="
        npx jest --testPathPattern {{ testFiles }} --testResultsProcessor=jest-junit --outputFile tmp/jest-node-${CIRCLE_NODE_INDEX}.xml
      delimiter: '|'
      globs:
        - 'tests/**/*.test.js'

cloud:
  disabled: false
    
