test-suites:
  it-rwx-jest:
    command: npx jest --json --testLocationInResults --outputFile tmp/jest.json
    results:
      path: tmp/jest.json
    output:
      print-summary: true
    partition:
      command: npx jest --testPathPattern {{ testFiles }} --json --testLocationInResults --outputFile tmp/jest.json
      delimiter: '|'
      globs:
        - 'tests/**/*.test.js'

# Captain Cloud configuration
cloud:
  enabled: true
  # The access token will be provided via RWX_ACCESS_TOKEN environment variable
