test-suites:
  it-rwx-jest:
    command: npx jest --json --testLocationInResults --outputFile tmp/jest.json
    results:
      path: tmp/jest.json
    output:
      print-summary: true
    partition:
      command: npx jest {{ testFiles }} --json --testLocationInResults --coverage --outputFile tmp/jest.json
      # command: npx jest --testPathPattern '{{ testFiles }}' --json --testLocationInResults --outputFile tmp/jest.json
      # delimiter: "|"
      globs:
        - "tests2/**/*.test.js"
    cloud:
      disabled: false
