test-suites:
  it-rwx-jest:
    command: npx jest --json --testLocationInResults --outputFile tmp/jest.json
    results:
      path: tmp/jest.json
    output:
      print-summary: true
    partition:
      command: npx jest {{ testFiles }} --json --testLocationInResults --outputFile tmp/jest.json
      globs:
        - "tests2/**/*.test.js"
