test-suites:
  it-rwx-jest:
    command: npx jest --testResultsProcessor=jest-junit --outputFile tmp/jest.xml
    results:
      path: tmp/jest.xml
    output:
      print-summary: true
    partition:
      command: |
        echo "=== Captain Debug ==="
        echo "Running Jest with partitioned test files..."
        echo "====================="
        npx jest --testPathPattern {{ testFiles }} --testResultsProcessor=jest-junit --outputFile tmp/jest-node-${CIRCLE_NODE_INDEX}.xml
      delimiter: '|'
      globs:
        - 'tests/**/*.test.js'

cloud:
  disabled: false
    
