version: 2.1

parameters:
  image-tag:
    type: string
    default: "current"

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/project

jobs:
  test-react-functionality:
    executor: node-executor
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install Captain CLI
          command: |
            # Install Captain using official method from https://www.rwx.com/docs/captain/getting-started/installing-the-cli
            tmp="$(mktemp -d)/captain" && \
              curl -o "$tmp" -fsSL "https://releases.captain.build/v1/linux/x86_64/captain" && \
              sudo install "$tmp" /usr/local/bin && \
              rm "$tmp" && \
              captain --version
            echo "✅ Captain CLI installed successfully!"
      - run:
          name: Install npm dependencies
          command: |
            npm install
            echo "✅ All dependencies installed!"
      - run:
          name: Create tmp directory
          command: |
            mkdir -p tmp
            echo "✅ tmp directory created!"
      - run:
          name: Run Jest tests with Captain partitioning
          command: |
            captain run it-rwx-jest --partition-index ${CIRCLE_NODE_INDEX} --partition-total ${CIRCLE_NODE_TOTAL} --print-summary
            echo "✅ Jest tests completed on partition ${CIRCLE_NODE_INDEX} of ${CIRCLE_NODE_TOTAL}"
          environment:
            CI: true
            RWX_ACCESS_TOKEN: ${it-rwx}
      - store_test_results:
          path: tmp
      - store_artifacts:
          path: tmp
          destination: test-results

workflows:
  test:
    jobs:
      - test-react-functionality

  
  
